import { Dimensions } from "react-native";

export const DIM = {
	height: Dimensions.get("window").height,
	width: Dimensions.get("window").width,
};

export const COLORS = {
	white: "#fff",
	black: "#000",
	slate: "#D6DFE0",
	primary: "#e40042",
	light_primary: "#F181A1",
	light_yellow: "#FFF5C0",
	boxColor: "#E8E8E8",
	box_light: "#F8F3EB",
	gainsboro: "#DCDCDC",
};

export const Data = [
	{
		id: 1,
		src: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
		author: "Author_1",
		owner_email: "kheya@gmail.com",
		rent: "5$",
		rating: "4.0",
		owner: "Owner_1",
		return_date: "Sat, 02/23/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_3",
	},
	{
		id: 2,
		src: "https://www.mswordcoverpages.com/wp-content/uploads/2018/10/Book-cover-page-3-CRC.png",
		author: "Author_2",
		owner_email: "mugdho@gmail.com",
		rent: "6$",
		rating: "4.5",
		owner: "Owner_2",
		return_date: "Sun, 02/24/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_1",
	},
	{
		id: 3,
		src: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1540569314l/42443467._SY475_.jpg",
		author: "Lyndee Walker",
		owner_email: "lyndee@gmail.com",
		rent: "3$",
		rating: "5.0",
		owner: "Owner_4",
		return_date: "Sat, 02/20/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_2",
	},
	{
		id: 4,
		src: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
		author: "John Hurley",
		owner_email: "john@gmail.com",
		rent: "5$",
		rating: "3.0",
		owner: "Owner_5",
		return_date: "Tue, 02/14/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_4",
	},
	{
		id: 5,
		src: "https://www.mswordcoverpages.com/wp-content/uploads/2018/10/Book-cover-page-3-CRC.png",
		author: "Author_2",
		owner_email: "mugdho@gmail.com",
		rent: "6$",
		rating: "4.0",
		owner: "Owner_2",
		return_date: "Mon, 02/13/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_1",
	},
	{
		id: 6,
		src: "https://www.mswordcoverpages.com/wp-content/uploads/2018/10/Book-cover-page-3-CRC.png",
		author: "Author_2",
		owner_email: "teelok@gmail.com",
		rent: "6$",
		rating: "4.5",
		owner: "Owner_2",
		return_date: "Wed, 02/27/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_2",
	},
	{
		id: 7,
		src: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
		author: "John Hurley",
		owner_email: "sk@gmail.com",
		rent: "5$",
		rating: "5.0",
		owner: "Owner_5",
		return_date: "Thu, 02/21/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_2",
	},
];

export const UserData = [
	{
		id: 1,
		src: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
		author: "Author_1",
		rent: "5$",
		rating: "4.0",
		return_date: "Sat, 02/23/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_3",
	},
	{
		id: 2,
		src: "https://www.mswordcoverpages.com/wp-content/uploads/2018/10/Book-cover-page-3-CRC.png",
		author: "Author_2",
		rent: "6$",
		rating: "4.5",
		return_date: "Sun, 02/24/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_1",
	},
	{
		id: 3,
		src: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1540569314l/42443467._SY475_.jpg",
		author: "Lyndee Walker",
		rent: "3$",
		rating: "5.0",
		return_date: "Sat, 02/20/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_2",
	},
	{
		id: 4,
		src: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
		author: "John Hurley",
		rent: "5$",
		rating: "3.0",
		return_date: "Tue, 02/14/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_4",
	},
	{
		id: 5,
		src: "https://www.mswordcoverpages.com/wp-content/uploads/2018/10/Book-cover-page-3-CRC.png",
		author: "Author_2",
		rent: "6$",
		rating: "4.0",
		return_date: "Mon, 02/13/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_1",
	},
	{
		id: 6,
		src: "https://www.mswordcoverpages.com/wp-content/uploads/2018/10/Book-cover-page-3-CRC.png",
		author: "Author_2",
		rent: "6$",
		rating: "4.5",
		return_date: "Wed, 02/27/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_2",
	},
	{
		id: 7,
		src: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
		author: "John Hurley",
		rent: "5$",
		rating: "5.0",
		return_date: "Thu, 02/21/2022",
		return_time: "3.00pm",
		location_for_pickup: "Location_2",
	},
];
